# Generated by Django 3.1.6 on 2021-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-age']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-age']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
