# Generated by Django 3.1.6 on 2021-02-10 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='main_app.photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('ADVICE & RESOURCES-GENERAL', 'ADVICE & RESOURCES-GENERAL'), ('ADVICE & RESOURCES-CAREER', 'ADVICE & RESOURCES-CAREER'), ('BIPOC IN TECH', 'BIPOC IN TECH'), ('CAREER CHANGER', 'CAREER CHANGER'), ('CAREER DEVELOPMENT', 'CAREER DEVELOPMENT'), ('ENTREPRENEURSHIP', 'ENTREPRENEURSHIP'), ('IN THE WORKPLACE', 'IN THE WORKPLACE'), ('Q & A', 'Q & A'), ('MOMMY IN TECH', 'MOMMY IN TECH'), ('NETWORKING', 'NETWORKING'), ('NEW TO TECH', 'NEW TO TECH'), ('TECH SISTERHOOD', 'TECH SISTERHOOD'), ('TECH TALK', 'TECH TALK')], default='Q & A', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='it_area',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Business Intelligence', 'Business Intelligence'), ('Cyber Security', 'Cyber Security'), ('Cloud', 'Cloud'), ('Data Management', 'Data Management'), ('Database', 'Database'), ('Game Development', 'Game Development'), ('Geographic IT', 'Geographic IT'), ('Healthcare IT', 'Healthcare IT'), ('IT Audit', 'IT Audit'), ('IT Coordinator', 'IT Coordinator'), ('IT Executive', 'IT Executive'), ('IT Management', 'IT Management'), ('IT Project', 'IT Project'), ('IT Specialist', 'IT Specialist'), ('IT Training', 'IT Training'), ('Network', 'Network'), ('Software Developer', 'Software Developer'), ('Software Management', 'Software Management'), ('Software Quality', 'Software Quality'), ('System Administator', 'System Administator'), ('System Analyst', 'System Analyst')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('Washington D.C.', 'Washington D.C.'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.TextField(default=2, validators=[django.core.validators.MinLengthValidator(2, 'Please submit a reply of with at least 2 characters')]),
            preserve_default=False,
        ),
    ]
