# Generated by Django 3.1.6 on 2021-02-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210210_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('ADVICE & RESOURCES-GENERAL', 'ADVICE & RESOURCES-GENERAL'), ('ADVICE & RESOURCES-CAREER', 'ADVICE & RESOURCES-CAREER'), ('BIPOC IN TECH', 'BIPOC IN TECH'), ('CAREER CHANGER', 'CAREER CHANGER'), ('CAREER DEVELOPMENT', 'CAREER DEVELOPMENT'), ('ENTREPRENEURSHIP', 'ENTREPRENEURSHIP'), ('IN THE WORKPLACE', 'IN THE WORKPLACE'), ('Q & A', 'Q & A'), ('MOMMY IN TECH', 'MOMMY IN TECH'), ('NETWORKING', 'NETWORKING'), ('NEW TO TECH', 'NEW TO TECH'), ('TECH SISTERHOOD', 'TECH SISTERHOOD'), ('TECH TALK', 'TECH TALK')], default='Q & A', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='it_area',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Business Intelligence', 'Business Intelligence'), ('Cyber Security', 'Cyber Security'), ('Cloud', 'Cloud'), ('Data Management', 'Data Management'), ('Database', 'Database'), ('Game Development', 'Game Development'), ('Geographic IT', 'Geographic IT'), ('Healthcare IT', 'Healthcare IT'), ('IT Audit', 'IT Audit'), ('IT Coordinator', 'IT Coordinator'), ('IT Executive', 'IT Executive'), ('IT Management', 'IT Management'), ('IT Project', 'IT Project'), ('IT Specialist', 'IT Specialist'), ('IT Training', 'IT Training'), ('Network', 'Network'), ('Software Developer', 'Software Developer'), ('Software Management', 'Software Management'), ('Software Quality', 'Software Quality'), ('System Administator', 'System Administator'), ('System Analyst', 'System Analyst')], default=0, max_length=50),
        ),
    ]
