# Generated by Django 3.1.6 on 2021-02-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210208_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='age',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='age',
        ),
    ]
