# Generated by Django 3.1.6 on 2021-02-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210209_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='avatar',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
