# Generated by Django 3.1.6 on 2021-02-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210205_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='email',
        ),
    ]
