# Generated by Django 3.1.6 on 2021-02-10 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210210_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.TextField(default=2, validators=[django.core.validators.MinLengthValidator(2, 'Please submit a reply of with at least 2 characters')]),
            preserve_default=False,
        ),
    ]
