# Generated by Django 3.1.6 on 2021-02-05 04:36

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210205_0232'),
    ]


