# Generated by Django 3.1.6 on 2021-02-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210210_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='profile',
            new_name='user',
        ),
    ]
