# Generated by Django 3.1.6 on 2021-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210205_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
