# Generated by Django 3.1.6 on 2021-02-07 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_auto_20210206_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='replies',
            field=models.ManyToManyField(related_name='replies', through='main_app.Reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='replies',
            field=models.ManyToManyField(related_name='replies', to='main_app.Reply'),
        ),
    ]
