# Generated by Django 3.1.6 on 2021-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210207_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('GA', 'ADVICE & RESOURCES-GENERAL'), ('CA', 'ADVICE & RESOURCES-CAREER'), ('WC', 'BIPOC IN TECH'), ('CC', 'CAREER CHANGER'), ('CD', 'CAREER DEVELOPMENT'), ('EN', 'ENTREPRENEURSHIP'), ('WP', 'IN THE WORKPLACE'), ('QA', 'Q & A'), ('MO', 'MOMMY IN TECH'), ('NW', 'NETWORKING'), ('NT', 'NEW TO TECH'), ('SH', 'TECH SISTERHOOD'), ('TC', 'TECH TALK')], default=0, max_length=50),
        ),
    ]
